@startuml


actor Buyer as buyer

actor Seller as seller

seller -down-> abstract_interface
buyer -down-> abstract_interface



node "Abstract Interface" as "abstract_interface" {


    frame "Web Interface" as web_interface {

    }

    frame "Mobile Interface" as "mobile_interface" {

    }

}


web_interface <--> backend_api
mobile_interface <--> backend_api
backend_api <--> firebase
backend_api <-> escrow_dapp

node "Backend API" as backend_api {

}


note right of backend_api
  Database of sellers \ buyers
  Google SSO
  Interaction with Ethereum
end note

cloud "Ethereum" as ethereum {
    card "Escrow dapp" as escrow_dapp {

    }
}


cloud Firebase as firebase {

}


@enduml